
try {
    console.log('inside try');
    console.log(student);
    console.log('after error');

}
catch(error){
    console.log('inside catch');
    // console.log(error);
}
finally {
    console.log('inside finally');
}